name: CI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: erlef/setup-elixir@v1
      with:
        otp-version: '24'
        elixir-version: 1.15.8
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        components: clippy
        override: true
    - run: cargo clippy --all-targets --all-features -- -D warnings
      working-directory: ./native

  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        components: rustfmt
        override: true
    - uses: erlef/setup-elixir@v1
      with:
        otp-version: '24'
        elixir-version: 1.15.8
    - run: cargo fmt --all -- --check
      working-directory: ./native
    - run: mix format --check-formatted

  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust-version:
        - stable
        - nightly
        - nightly-2021-01-25
        beam-pair:
        - otp-version: '24'
          elixir-version: 1.11.4
        - otp-version: '24'
          elixir-version: 1.12.2
        - otp-version: '24'
          elixir-version: 1.15.8
        - otp-version: '25'
          elixir-version: 1.15.8
        - otp-version: '25'
          elixir-version: 1.18.1
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust-version }}
        components: clippy, rustfmt
    - uses: erlef/setup-beam@v1
      with:
        elixir-version: ${{ matrix.beam-pair.elixir-version }}
        otp-version: ${{ matrix.beam-pair.otp-version }}
    - run: cargo build
      working-directory: ./native
    - run: mix deps.get
    - run: mix compile
